career:
  message: null
  overalldeveloptime: null
  overalldeveloptimeperrun: null
  overalldeveloptimeunit: null
  overallruncounter: null
  overallsavedunit: null
  overalltimesaved: null
  overalltotaldevelopcounter: null
debug:
  developtimeperrun: time.timestamp()
  developtimeunit: minutes
  totaldevelopcounter: 0
  totaldevelopertimeused: 0
listingproject:
  message: 'Times Ran: 3

    Time Saved: 15 minutes

    '
  timesavedperrun: 5
  timesavedunit: minutes
  totalruncounter: 3
  totaltimesaved: 15
manifestproject: null
salesproject: null
taxesproject:
  message: 'Times Ran: 34

    Time Saved: 34 hours

    '
  timesavedperrun: 1
  timesavedunit: hours
  totalruncounter: 0
  totaltimesaved: 0
